[package]
name = "octosense-reference"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
makepad-widgets = { git = "https://github.com/OctoSense-org/makepad.git", rev = "9069cfaf87960f535f2440d736d223238b88c5b1" }
makepad-app-module = { git = "https://github.com/OctoSense-org/makepad.git", rev = "9069cfaf87960f535f2440d736d223238b88c5b1" }
