[package]
name = "octosense-reference"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
makepad-widgets = { git = "https://github.com/OctoSense-org/makepad.git", rev = "e596207afc75fdc22d84ec0fbd5b99bef7139808" }
makepad-app-module = { git = "https://github.com/OctoSense-org/makepad.git", rev = "e596207afc75fdc22d84ec0fbd5b99bef7139808" }
