#!/usr/bin/env python3
"""Build the Home/Bridge APK pair for ordinary Android or OctoSense ROM.

Home's octos kernel is a shell service (feature `octos-core`, on in every
phone build): the APK bundles it as `liboctos.so`, the only place an Android
app may exec a binary from. By default the kernel is cross-built from the one
octos revision Home's Cargo.lock pins; `--octos-kernel` bundles a prebuilt
one, `--no-octos-kernel` leaves it out (Home then runs no kernel; the AI
providers are still saved).
"""
import argparse
import glob
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
OCTOS_URL = "https://github.com/octos-org/octos.git"
# The kernel as the shells' phones run it: the stdio server, no llama.cpp
# embedder (needs cmake and is not used on a phone).
OCTOS_KERNEL_BUILD = ["-p", "octos-cli", "--bin", "octos", "--no-default-features", "--features", "api,git,ast"]
ANDROID_TARGET = "aarch64-linux-android"
ANDROID_API = "33"


def octos_revision(lock=None):
    """The one octos revision Home links (home/Cargo.lock)."""
    text = (lock or ROOT / "home/Cargo.lock").read_text()
    match = re.search(r'name = "octos-cli"\nversion = "[^"]+"\nsource = "git\+https://github\.com/octos-org/octos\.git\?rev=([0-9a-f]{40})#', text)
    if not match:
        raise RuntimeError("home/Cargo.lock names no octos-cli from octos-org/octos: cannot tell which kernel to build")
    return match[1]


def ndk_bin(sdk):
    """The NDK's LLVM bin dir inside the cargo-makepad SDK directory (newest NDK)."""
    found = sorted(glob.glob(str(sdk / "ndk/*/toolchains/llvm/prebuilt/*/bin")),
                   key=lambda p: [int(x) if x.isdigit() else x for x in re.split(r"[./]", p)])
    return Path(found[-1]) if found else sdk / "ndk/<version>/toolchains/llvm/prebuilt/<host>/bin"


def kernel_build_command(sdk, offline):
    """Cross-build the kernel with the NDK's clang, as AppCard's build-android.sh does."""
    bin_dir = ndk_bin(sdk)
    clang = bin_dir / f"{ANDROID_TARGET}{ANDROID_API}-clang"
    env = {"CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER": clang,
           "CARGO_TARGET_AARCH64_LINUX_ANDROID_AR": bin_dir / "llvm-ar",
           "CC_aarch64_linux_android": clang,
           "CXX_aarch64_linux_android": bin_dir / f"{ANDROID_TARGET}{ANDROID_API}-clang++",
           "AR_aarch64_linux_android": bin_dir / "llvm-ar",
           "RANLIB_aarch64_linux_android": bin_dir / "llvm-ranlib"}
    command = ["env", *(f"{k}={v}" for k, v in env.items()),
               "cargo", "build", "--locked", "--release", "--target", ANDROID_TARGET, *OCTOS_KERNEL_BUILD]
    if offline:
        command.append("--offline")
    return command


def arguments(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--variant", required=True, choices=("standalone", "rom"))
    p.add_argument("--sdk", required=True, type=Path, help="Prepared cargo-makepad Android SDK/NDK/JDK directory")
    p.add_argument("--android-sdk", required=True, type=Path, help="Android SDK with platform 35 and build-tools 35.0.0")
    p.add_argument("--gradle-home", type=Path, help="Installed Gradle 8.11.1 distribution (or use PATH)")
    p.add_argument("--java-home", type=Path, default=os.environ.get("JAVA_HOME"), help="Full installed JDK 17+ for Gradle; defaults to JAVA_HOME")
    p.add_argument("--packager", type=Path, help="Use an already built cargo-makepad; otherwise build the pinned source")
    p.add_argument("--sign-key", type=Path, help="Existing signer PKCS#8 key; never generated by this command")
    p.add_argument("--sign-cert", type=Path, help="Existing signer X.509 certificate")
    p.add_argument("--development", action="store_true", help="Standalone only: sign both APKs with Makepad's development keystore")
    p.add_argument("--version-code", default="auto")
    p.add_argument("--output", type=Path)
    p.add_argument("--offline", action="store_true")
    kernel = p.add_mutually_exclusive_group()
    kernel.add_argument("--octos-kernel", type=Path, help="Bundle this prebuilt aarch64-linux-android `octos` as liboctos.so instead of building it")
    kernel.add_argument("--no-octos-kernel", action="store_true", help="Bundle no octos kernel (Home then runs none)")
    p.add_argument("--dry-run", action="store_true", help="Print the build plan without executing or signing")
    args = p.parse_args(argv)
    if bool(args.sign_key) != bool(args.sign_cert):
        p.error("--sign-key and --sign-cert must be supplied together")
    if args.development and (args.variant != "standalone" or args.sign_key):
        p.error("--development is only for standalone builds without release keys")
    if not args.development and not args.sign_key:
        p.error("Supply the existing signer with --sign-key/--sign-cert, or use --development for standalone testing")
    if args.version_code != "auto" and (not args.version_code.isdigit() or not 0 < int(args.version_code) < 2100000000):
        p.error("--version-code must be auto or a positive Android version code")
    for name in ("sdk", "android_sdk", "gradle_home", "java_home", "packager", "sign_key", "sign_cert", "output", "octos_kernel"):
        if getattr(args, name):
            setattr(args, name, Path(getattr(args, name)).resolve())
    args.java_home = args.java_home or args.sdk / "openjdk"
    args.output = args.output or ROOT / "out/home" / args.variant
    return args


def kernel_plan(args):
    """(steps, kernel path or None) for the octos kernel the APK bundles."""
    if args.no_octos_kernel:
        return [], None
    if args.octos_kernel:
        return [], args.octos_kernel
    source = ROOT / ".sources/octos"
    revision = octos_revision()
    steps = [(ROOT, ["git", "init", "--quiet", str(source)])]
    if not args.offline:
        steps.append((source, ["git", "fetch", "--quiet", "--no-tags", "--depth=1", OCTOS_URL, revision]))
    steps += [(source, ["git", "checkout", "--quiet", "--detach", revision]),
              (source, kernel_build_command(args.sdk, args.offline))]
    return steps, source / "target" / ANDROID_TARGET / "release/octos"


def extra_libs(kernel):
    """cargo-makepad's MAKEPAD_ANDROID_EXTRA_LIBS for the kernel."""
    return f"liboctos.so={kernel}" if kernel else None


def build_plan(args):
    sources = ROOT / ".sources"
    cargo = ["cargo", "build", "--locked", "--release", "--manifest-path", str(sources / "makepad/tools/cargo_makepad/Cargo.toml")]
    gradle = [str(ROOT / "home/android/gradlew"), "--no-daemon", ":contracts:exportHomeContracts", ":system-bridge:assembleRelease"]
    packager = args.packager or sources / "makepad/target/release/cargo-makepad"
    android = [str(packager), "makepad", "android", f"--sdk-path={args.sdk}", "--abi=aarch64", f"--version-code={args.version_code}", "--no-sign", "build", "-p", "octosense", "--release", "--locked"]
    if args.offline:
        cargo.append("--offline")
        gradle.append("--offline")
        android.append("--offline")
    plan = [(ROOT, [sys.executable, str(ROOT / "scripts/setup-home.py"), "--check"])]
    if not args.packager:
        plan.append((sources / "makepad", cargo))
    plan += kernel_plan(args)[0]
    return plan + [(ROOT / "home/android", gradle), (ROOT / "home", android)]


def certificate_digest(apksigner, apk, env):
    output = subprocess.check_output([str(apksigner), "verify", "--print-certs", str(apk)], env=env, text=True)
    match = re.search(r"Signer #1 certificate SHA-256 digest: ([0-9a-f]+)", output)
    if not match:
        raise RuntimeError(f"No verified signing certificate for {apk.name}")
    return match[1]


def main(argv=None):
    args = arguments(argv)
    plan = build_plan(args)
    kernel = kernel_plan(args)[1]
    if args.dry_run:
        print(json.dumps({"variant": args.variant, "development": args.development,
                          "output": str(args.output),
                          "octos_kernel": str(kernel) if kernel else None,
                          "android_env": {"MAKEPAD_ANDROID_EXTRA_LIBS": extra_libs(kernel)},
                          "steps": [
                              {"cwd": str(cwd), "argv": command} for cwd, command in plan],
                          "artifacts": ["OctoSenseHome.apk", "OctoSenseBridge.apk", "build.json"],
                          "installs_or_flashes": False}, indent=2))
        return
    sources = ROOT / ".sources"
    for path in (args.java_home / "bin/java", args.android_sdk / "platforms/android-35/android.jar",
                 args.android_sdk / "build-tools/35.0.0/apksigner"):
        if not path.is_file():
            raise RuntimeError(f"Required Android tool missing: {path}")
    if args.octos_kernel and not args.octos_kernel.is_file():
        raise RuntimeError(f"The octos kernel to bundle does not exist: {args.octos_kernel}")
    if kernel and not args.octos_kernel and not (ndk_bin(args.sdk) / f"{ANDROID_TARGET}{ANDROID_API}-clang").is_file():
        raise RuntimeError(f"No NDK clang to build the octos kernel with under {args.sdk}/ndk (or pass --octos-kernel / --no-octos-kernel)")
    if args.sign_key:
        for path in (args.sign_key, args.sign_cert):
            if not path.is_file():
                raise RuntimeError(f"Signing input does not exist: {path}")
            if path.is_relative_to(ROOT):
                raise RuntimeError("Keep signing keys and certificates outside the product checkout")
    env = dict(os.environ)
    env.update(JAVA_HOME=str(args.java_home), ANDROID_HOME=str(args.android_sdk),
               ANDROID_SDK_ROOT=str(args.android_sdk), OCTOSENSE_WORKSPACE=str(sources))
    env["PATH"] = str(args.java_home / "bin") + os.pathsep + env.get("PATH", "")
    # Always build the unsigned Bridge release and sign the pair together below.
    env.pop("OCTOSENSE_KEYSTORE", None)
    env.pop("CARGO_TARGET_DIR", None)
    if args.gradle_home:
        env["OCTOSENSE_GRADLE_HOME"] = str(args.gradle_home)
    env["RUSTFLAGS"] = (env.get("RUSTFLAGS", "") + f" --remap-path-prefix={ROOT}=/octosense-rom --remap-path-prefix={Path.home()}=/build").strip()
    env.pop("MAKEPAD_ANDROID_EXTRA_LIBS", None)
    if kernel:
        env["MAKEPAD_ANDROID_EXTRA_LIBS"] = extra_libs(kernel)
    for cwd, command in plan:
        if kernel and command[0] == str(args.packager or sources / "makepad/target/release/cargo-makepad") and not kernel.is_file():
            raise RuntimeError(f"The octos kernel was not built: {kernel}")
        subprocess.run(command, cwd=cwd, env=env, check=True)
    inputs = {
        "OctoSenseHome.apk": ROOT / "home/target/android/makepad-android-apk/octosense/apk/octo_sense.apk",
        "OctoSenseBridge.apk": ROOT / "home/android/system-bridge/build/outputs/apk/release/system-bridge-release-unsigned.apk",
    }
    args.output.mkdir(parents=True, exist_ok=True)
    apksigner = args.android_sdk / "build-tools/35.0.0/apksigner"
    artifacts = {}
    for name, source in inputs.items():
        destination = args.output / name
        temporary = destination.with_suffix(".pending.apk")
        command = [str(apksigner), "sign"]
        if args.development:
            command += ["--ks", str(sources / "makepad/tools/cargo_makepad/debug.keystore"),
                        "--ks-key-alias", "androiddebugkey", "--ks-pass", "pass:android", "--key-pass", "pass:android"]
        else:
            command += ["--key", str(args.sign_key), "--cert", str(args.sign_cert)]
        subprocess.run(command + ["--out", str(temporary), str(source)], env=env, check=True)
        digest = certificate_digest(apksigner, temporary, env)
        temporary.replace(destination)
        artifacts[name] = {"sha256": hashlib.sha256(destination.read_bytes()).hexdigest(), "certificate_sha256": digest}
    if len({item["certificate_sha256"] for item in artifacts.values()}) != 1:
        raise RuntimeError("Home and Bridge must have the same signing identity")
    aapt = args.android_sdk / "build-tools/35.0.0/aapt2"
    badging = subprocess.check_output([str(aapt), "dump", "badging", str(args.output / "OctoSenseHome.apk")], env=env, text=True)
    version = re.search(r"versionCode='([0-9]+)'", badging).group(1)
    receipt = {"schema_version": 1, "variant": args.variant, "development": args.development,
               "home_version_code": int(version),
               "source_revision": subprocess.check_output(["git", "-C", str(ROOT), "rev-parse", "HEAD"], text=True).strip(),
               "source_dirty": bool(subprocess.check_output(["git", "-C", str(ROOT), "status", "--porcelain"], text=True)),
               "runtime": json.loads((ROOT / "home/native-runtime.lock.json").read_text()),
               "runtime_patches": json.loads((ROOT / "home/runtime-patches.lock.json").read_text()),
               "packager": str(args.packager) if args.packager else "pinned source",
               "native_apps": json.loads((ROOT / "home/native-apps.lock.json").read_text()),
               "octos_kernel": None if not kernel else {
                   "source": "prebuilt" if args.octos_kernel else f"{OCTOS_URL}@{octos_revision()}",
                   "sha256": hashlib.sha256(kernel.read_bytes()).hexdigest()},
               "artifacts": artifacts}
    (args.output / "build.json").write_text(json.dumps(receipt, indent=2) + "\n")
    print(f"Built {args.variant} Home {version} and Bridge in {args.output}")


if __name__ == "__main__":
    main()
