#!/usr/bin/env python3
"""Build the Home/Bridge APK pair for ordinary Android or OctoSense ROM.

Home's octos kernel is a shell service (feature `octos-core`, on in every
phone build): the APK bundles it as `liboctos.so`, the only place an Android
app may exec a binary from. By default the kernel is cross-built from the one
octos revision the workspace Cargo.lock pins; `--octos-kernel` bundles a prebuilt
one, `--no-octos-kernel` leaves it out (Home then runs no kernel; the AI
providers are still saved).
"""
import argparse
from datetime import datetime, timezone
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import zipfile

ROOT = Path(__file__).resolve().parents[1]
# The OctoSense repository: Home is phone/, the workspace lock and the
# framework checkouts (.sources/, tools/setup.py) are at its root.
REPO = ROOT.parent
HOME = REPO / "phone"


def _load_kernel_tool():
    """The shared octos kernel tool (tools/kernel-artifact.py): one kernel
    recipe for every shell's APK."""
    spec = importlib.util.spec_from_file_location("kernel_artifact", REPO / "tools/kernel-artifact.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


kernel_tool = _load_kernel_tool()
OCTOS_URL = kernel_tool.OCTOS_URL
OCTOS_KERNEL_BUILD = kernel_tool.KERNEL_BUILD
ANDROID_TARGET = kernel_tool.TARGET
ANDROID_API = kernel_tool.API
extra_libs = kernel_tool.extra_libs


def octos_revision(lock=None):
    """The one octos revision Home links (the workspace Cargo.lock)."""
    return kernel_tool.octos_revision(lock or REPO / "Cargo.lock")


def arguments(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--variant", required=True, choices=("standalone", "rom"))
    p.add_argument("--sdk", required=True, type=Path, help="Prepared cargo-makepad Android SDK/NDK/JDK directory")
    p.add_argument("--android-sdk", required=True, type=Path, help="Android SDK with platform 35 and build-tools 35.0.0")
    p.add_argument("--gradle-home", type=Path, help="Installed Gradle 8.11.1 distribution (or use PATH)")
    p.add_argument("--java-home", type=Path, default=os.environ.get("JAVA_HOME"), help="Full installed JDK 17+ for Gradle; defaults to JAVA_HOME")
    p.add_argument("--packager", type=Path, help="Use an already built cargo-makepad; otherwise build the pinned source")
    p.add_argument("--sign-key", type=Path, help="Existing signer PKCS#8 key; never generated by this command")
    p.add_argument("--sign-cert", type=Path, help="Existing signer X.509 certificate")
    p.add_argument("--development", action="store_true", help="Standalone only: sign both APKs with Makepad's development keystore")
    p.add_argument("--version-code", default="auto")
    p.add_argument("--version-name", help="Version name for both Home and Bridge (for example 0.1.0-beta.2)")
    p.add_argument("--expected-signer", help="Require this existing certificate SHA-256 digest on both APKs")
    p.add_argument("--output", type=Path)
    p.add_argument("--offline", action="store_true")
    kernel = p.add_mutually_exclusive_group()
    kernel.add_argument("--octos-kernel", type=Path, help="Bundle this prebuilt aarch64-linux-android `octos` as liboctos.so instead of building it")
    kernel.add_argument("--no-octos-kernel", action="store_true", help="Bundle no octos kernel (Home then runs none)")
    p.add_argument("--dry-run", action="store_true", help="Print the build plan without executing or signing")
    args = p.parse_args(argv)
    if bool(args.sign_key) != bool(args.sign_cert):
        p.error("--sign-key and --sign-cert must be supplied together")
    if args.development and (args.variant != "standalone" or args.sign_key):
        p.error("--development is only for standalone builds without release keys")
    if not args.development and not args.sign_key:
        p.error("Supply the existing signer with --sign-key/--sign-cert, or use --development for standalone testing")
    if args.version_code != "auto" and (not args.version_code.isdigit() or not 0 < int(args.version_code) < 2100000000):
        p.error("--version-code must be auto or a positive Android version code")
    # Resolve once: Gradle and cargo-makepad must not cross an hour boundary
    # and assign different versions to the same release pair.
    if args.version_code == "auto":
        args.version_code = datetime.now(timezone.utc).strftime("%Y%m%d%H")
    if args.version_name is not None and not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9.+_-]{0,63}", args.version_name):
        p.error("--version-name must be 1-64 letters, digits, dots, plus signs, underscores or hyphens")
    if args.expected_signer:
        if not re.fullmatch(r"[0-9a-fA-F]{64}", args.expected_signer):
            p.error("--expected-signer must be a certificate SHA-256 digest")
        args.expected_signer = args.expected_signer.lower()
    for name in ("sdk", "android_sdk", "gradle_home", "java_home", "packager", "sign_key", "sign_cert", "output", "octos_kernel"):
        if getattr(args, name):
            setattr(args, name, Path(getattr(args, name)).resolve())
    args.java_home = args.java_home or args.sdk / "openjdk"
    args.output = args.output or ROOT / "out/home" / args.variant
    return args


def kernel_source(args):
    """(steps, kernel path or None, source) for the octos kernel the APK
    bundles: built from the locked revision under .sources/octos-kernel, a
    prebuilt one, or none."""
    return kernel_tool.kernel_plan(lock=REPO / "Cargo.lock", work=REPO / ".sources/octos-kernel", sdk=args.sdk,
                                   kernel=args.octos_kernel, no_kernel=args.no_octos_kernel,
                                   offline=args.offline, required=False)


def kernel_plan(args):
    """(steps, kernel path or None) for the octos kernel the APK bundles."""
    return kernel_source(args)[:2]


def build_plan(args):
    sources = REPO / ".sources"
    cargo = ["cargo", "build", "--locked", "--release", "--manifest-path", str(sources / "makepad/tools/cargo_makepad/Cargo.toml")]
    gradle = [str(HOME / "android/gradlew"), "--no-daemon", f"-PoctosenseVersionCode={args.version_code}", ":contracts:exportHomeContracts", ":system-bridge:assembleRelease"]
    packager = args.packager or sources / "makepad/target/release/cargo-makepad"
    android = [str(packager), "makepad", "android", f"--sdk-path={args.sdk}", "--abi=aarch64", f"--version-code={args.version_code}", "--no-sign", "build", "-p", "octosense-home", "--release", "--locked"]
    if args.version_name is not None:
        gradle.insert(2, f"-PoctosenseVersionName={args.version_name}")
        android.insert(android.index("build"), f"--version-name={args.version_name}")
    if args.offline:
        cargo.append("--offline")
        gradle.append("--offline")
        android.append("--offline")
    plan = [(REPO, [sys.executable, str(REPO / "tools/setup.py"), "--check"])]
    if not args.packager:
        plan.append((sources / "makepad", cargo))
    plan += kernel_plan(args)[0]
    return plan + [(HOME / "android", gradle), (HOME, android)]


def rustflags(env):
    """RUSTFLAGS with the build's own paths remapped out of panic locations
    and file!(): the checkout, CARGO_HOME (registry and git dependencies)
    and the home directory."""
    cargo_home = Path(env.get("CARGO_HOME") or Path.home() / ".cargo").resolve()
    remaps = [f"--remap-path-prefix={Path.home()}=/build",
              f"--remap-path-prefix={cargo_home}=/cargo",
              f"--remap-path-prefix={REPO}=/octosense"]
    return " ".join([env.get("RUSTFLAGS", "").strip(), *remaps]).strip()


def updater_identity(args):
    """Only the explicit standalone release version is a public updater
    identity. ROM and development builds cannot inherit a stale release tag
    from the shell and then request an incompatible standalone package."""
    version = args.version_name
    number = r"(?:0|[1-9][0-9]*)"
    if (args.variant == "standalone" and not args.development and version
            and re.fullmatch(rf"{number}\.{number}\.{number}(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?", version)):
        if "-" in version:
            prerelease = version.split("-", 1)[1]
            if any(part.isdigit() and len(part) > 1 and part.startswith("0") for part in prerelease.split(".")):
                return ""
        return f"home-v{version}"
    return ""


# What a published (ROM) Home must not carry in its native libraries.
# `--remap-path-prefix` cannot reach env!("CARGO_MANIFEST_DIR"), which every
# `script_mod!` compiles in, so a ROM build must run from a checkout (and
# CARGO_HOME) outside any home directory.
def personal_paths(apk, home=None):
    """{library: [marker, ...]} for native libraries that carry a home
    directory path."""
    markers = [b"/Users/", str(home or Path.home()).encode()]
    found = {}
    with zipfile.ZipFile(apk) as archive:
        for name in archive.namelist():
            if name.startswith("lib/") and name.endswith(".so"):
                data = archive.read(name)
                hits = [m.decode() for m in markers if m in data]
                if hits:
                    found[name] = sorted(set(hits))
    return found


def certificate_digest(apksigner, apk, env):
    output = subprocess.check_output([str(apksigner), "verify", "--print-certs", str(apk)], env=env, text=True)
    match = re.search(r"Signer #1 certificate SHA-256 digest: ([0-9a-f]+)", output)
    if not match:
        raise RuntimeError(f"No verified signing certificate for {apk.name}")
    return match[1]


def apk_metadata(aapt, apk, env):
    badging = subprocess.check_output([str(aapt), "dump", "badging", str(apk)], env=env, text=True)
    match = re.search(r"^package: name='([^']+)' versionCode='([0-9]+)' versionName='([^']*)'", badging, re.MULTILINE)
    if not match:
        raise RuntimeError(f"No package/version metadata for {apk.name}")
    return {"package_name": match[1], "version_code": int(match[2]), "version_name": match[3]}


def verify_pair(artifacts, args):
    expected_packages = {"OctoSenseHome.apk": "dev.makepad.octosense", "OctoSenseBridge.apk": "dev.makepad.octosense.bridge"}
    for name, package in expected_packages.items():
        item = artifacts[name]
        if item["package_name"] != package or item["version_code"] != int(args.version_code):
            raise RuntimeError(f"{name} package/version does not match the requested release")
        if args.version_name is not None and item["version_name"] != args.version_name:
            raise RuntimeError(f"{name} version name does not match the requested release")
        if args.expected_signer and item["certificate_sha256"] != args.expected_signer:
            raise RuntimeError(f"{name} does not have the required existing signing identity")
    if len({item["certificate_sha256"] for item in artifacts.values()}) != 1:
        raise RuntimeError("Home and Bridge must have the same signing identity")


def main(argv=None):
    args = arguments(argv)
    plan = build_plan(args)
    kernel = kernel_plan(args)[1]
    if args.dry_run:
        print(json.dumps({"variant": args.variant, "development": args.development,
                          "output": str(args.output), "version_code": int(args.version_code),
                          "version_name": args.version_name, "expected_signer": args.expected_signer,
                          "octos_kernel": str(kernel) if kernel else None,
                          "android_env": {"MAKEPAD_ANDROID_EXTRA_LIBS": extra_libs(kernel),
                                          "OCTOSENSE_RELEASE_TAG": updater_identity(args)},
                          "steps": [
                              {"cwd": str(cwd), "argv": command} for cwd, command in plan],
                          "artifacts": ["OctoSenseHome.apk", "OctoSenseBridge.apk", "build.json"],
                          "installs_or_flashes": False}, indent=2))
        return
    sources = REPO / ".sources"
    for path in (args.java_home / "bin/java", args.android_sdk / "platforms/android-35/android.jar",
                 args.android_sdk / "build-tools/35.0.0/apksigner"):
        if not path.is_file():
            raise RuntimeError(f"Required Android tool missing: {path}")
    if args.octos_kernel and not args.octos_kernel.is_file():
        raise RuntimeError(f"The octos kernel to bundle does not exist: {args.octos_kernel}")
    if kernel and not args.octos_kernel and not (kernel_tool.ndk_bin(args.sdk, required=False) / f"{ANDROID_TARGET}{ANDROID_API}-clang").is_file():
        raise RuntimeError(f"No NDK clang to build the octos kernel with under {args.sdk}/ndk (or pass --octos-kernel / --no-octos-kernel)")
    if args.sign_key:
        for path in (args.sign_key, args.sign_cert):
            if not path.is_file():
                raise RuntimeError(f"Signing input does not exist: {path}")
            if path.is_relative_to(REPO):
                raise RuntimeError("Keep signing keys and certificates outside the product checkout")
    env = dict(os.environ)
    env.update(JAVA_HOME=str(args.java_home), ANDROID_HOME=str(args.android_sdk),
               ANDROID_SDK_ROOT=str(args.android_sdk), OCTOSENSE_WORKSPACE=str(sources),
               OCTOSENSE_RELEASE_TAG=updater_identity(args))
    env["PATH"] = str(args.java_home / "bin") + os.pathsep + env.get("PATH", "")
    # Always build the unsigned Bridge release and sign the pair together below.
    env.pop("OCTOSENSE_KEYSTORE", None)
    env.pop("CARGO_TARGET_DIR", None)
    if args.gradle_home:
        env["OCTOSENSE_GRADLE_HOME"] = str(args.gradle_home)
    env["RUSTFLAGS"] = rustflags(env)
    env.pop("MAKEPAD_ANDROID_EXTRA_LIBS", None)
    if kernel:
        env["MAKEPAD_ANDROID_EXTRA_LIBS"] = extra_libs(kernel)
    for cwd, command in plan:
        if kernel and command[0] == str(args.packager or sources / "makepad/target/release/cargo-makepad") and not kernel.is_file():
            raise RuntimeError(f"The octos kernel was not built: {kernel}")
        # The kernel's work dir (.sources/octos-kernel) starts empty.
        Path(cwd).mkdir(parents=True, exist_ok=True)
        subprocess.run(command, cwd=cwd, env=env, check=True)
    inputs = {
        "OctoSenseHome.apk": HOME / "target/android/makepad-android-apk/octosense_home/apk/octo_sense.apk",
        "OctoSenseBridge.apk": HOME / "android/system-bridge/build/outputs/apk/release/system-bridge-release-unsigned.apk",
    }
    if args.variant == "rom":
        leaked = personal_paths(inputs["OctoSenseHome.apk"])
        if leaked:
            raise RuntimeError(f"ROM Home carries home-directory paths {leaked}: build from a checkout and "
                               "CARGO_HOME outside /Users (script_mod! compiles CARGO_MANIFEST_DIR in)")
    args.output.mkdir(parents=True, exist_ok=True)
    apksigner = args.android_sdk / "build-tools/35.0.0/apksigner"
    aapt = args.android_sdk / "build-tools/35.0.0/aapt2"
    artifacts = {}
    for name, source in inputs.items():
        destination = args.output / name
        temporary = destination.with_suffix(".pending.apk")
        command = [str(apksigner), "sign"]
        if args.development:
            command += ["--ks", str(sources / "makepad/tools/cargo_makepad/debug.keystore"),
                        "--ks-key-alias", "androiddebugkey", "--ks-pass", "pass:android", "--key-pass", "pass:android"]
        else:
            command += ["--key", str(args.sign_key), "--cert", str(args.sign_cert)]
        subprocess.run(command + ["--out", str(temporary), str(source)], env=env, check=True)
        digest = certificate_digest(apksigner, temporary, env)
        artifacts[name] = {"sha256": hashlib.sha256(temporary.read_bytes()).hexdigest(), "certificate_sha256": digest,
                           **apk_metadata(aapt, temporary, env)}
    # A stale Bridge or unexpected signing input must never replace a previous
    # good pair before both pending artifacts have been checked.
    verify_pair(artifacts, args)
    for name in inputs:
        destination = args.output / name
        destination.with_suffix(".pending.apk").replace(destination)
    home_version = artifacts["OctoSenseHome.apk"]
    bridge_version = artifacts["OctoSenseBridge.apk"]
    packager = args.packager or sources / "makepad/target/release/cargo-makepad"
    receipt = {"schema_version": 1, "variant": args.variant, "development": args.development,
               "release_tag": updater_identity(args) or None,
               "home_version_code": home_version["version_code"], "home_version_name": home_version["version_name"],
               "bridge_version_code": bridge_version["version_code"], "bridge_version_name": bridge_version["version_name"],
               "source_revision": subprocess.check_output(["git", "-C", str(REPO), "rev-parse", "HEAD"], text=True).strip(),
               "source_dirty": bool(subprocess.check_output(["git", "-C", str(REPO), "status", "--porcelain"], text=True)),
               "runtime": json.loads((REPO / "native-runtime.lock.json").read_text()),
               "runtime_patches": json.loads((REPO / "runtime-patches.lock.json").read_text()),
               "packager": "explicit override" if args.packager else "pinned source",
               "packager_sha256": hashlib.sha256(packager.read_bytes()).hexdigest(),
               "octos_kernel": kernel_tool.receipt(kernel, kernel_source(args)[2]),
               "artifacts": artifacts}
    (args.output / "build.json").write_text(json.dumps(receipt, indent=2) + "\n")
    print(f"Built {args.variant} Home {home_version['version_code']} and Bridge in {args.output}")


if __name__ == "__main__":
    main()
