[package]
name = "octosense-reference"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
makepad-widgets = { git = "https://github.com/OctoSense-org/makepad.git", rev = "712b9f16d1992131bb99c070673faa1929fe75f3" }
makepad-app-module = { git = "https://github.com/OctoSense-org/makepad.git", rev = "712b9f16d1992131bb99c070673faa1929fe75f3" }
